### ISSUE TITLE
Admin eror

### ISSUE THREAD

**Issue by ami-ach** [qaxim/blog#3]
Warning: require_once(/home/u83xtcew/public_html/admin/config.php): Failed to open stream: No such file or directory in /home/u83xtcew/public_html/app/vendor/xcrud/xcrud_db.php on line 5

Fatal error: Uncaught Error: Failed opening required '/home/u83xtcew/public_html/admin/config.php' (include_path='.:/opt/cpanel/ea-php81/root/usr/share/pear') in /home/u83xtcew/public_html/app/vendor/xcrud/xcrud_db.php:5 Stack trace: #0 /home/u83xtcew/public_html/app/vendor/xcrud/xcrud.php(11): require() #1 /home/u83xtcew/public_html/app/controllers/admin.php(82): include('/home/u83xtcew/...') #2 [internal function]: {closure}() #3 /home/u83xtcew/public_html/index.php(4): call_user_func_array(Object(Closure), Array) #4 /home/u83xtcew/public_html/index.php(4): AppRouter\Router->call(Object(Closure), Array) #5 /home/u83xtcew/public_html/index.php(4): AppRouter\Router->dispatch('GET', '/admin/categori...') #6 /home/u83xtcew/public_html/index.php(43): AppRouter\Router->dispatchGlobal() #7 {main} thrown in /home/u83xtcew/public_html/app/vendor/xcrud/xcrud_db.php on line 5

**Comment by Dacogetul** [comment]
This is a stolen app..from https://i.ibb.co/
